name: Generate Terraform Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
      - feature2
    paths:
      - '**/main.tf'
      - '**/variables.tf'
      - '**/README.md'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "terraform-docs: automated update"
          git-push-user-name: github-actions[bot]
          git-push-user-email: github-actions[bot]@users.noreply.github.com
